import {collectPage,promptFor,destination} from './core.js';
const $=id=>document.getElementById(id);
let data, courses={};
const api=globalThis.chrome?.runtime?.id;
const status=text=>{$('status').textContent=text;$('status').hidden=!text;};
function refresh(){if(!data)return;data.course=$('course').value;data.title=$('title').value;data.text=$('source').value;data.questions=$('questions').value.split('\n').filter(Boolean);const links=data.links.filter((_,i)=>$('resource-'+i).checked);$('prompt').value=promptFor({...data,links},{instructions:$('instructions').checked,context:$('context').checked,notes:$('notes').checked});$('counts').replaceChildren(...[`${links.length} readings`,`${links.filter(x=>x.pdf).length} PDFs`,`${data.questions.length} questions`].map(x=>{const s=document.createElement('span');s.textContent=x;return s;}));}
function render(result){data=result;$('review').hidden=false;$('course').value=data.course;$('title').value=data.title;$('source').value=data.text;$('questions').value=data.questions.join('\n');$('resources').replaceChildren();data.links.forEach((link,i)=>{const label=document.createElement('label');label.className='resource';const check=document.createElement('input');check.type='checkbox';check.id='resource-'+i;check.checked=true;check.onchange=refresh;const text=document.createElement('span');text.textContent=link.title;const small=document.createElement('small');small.textContent=link.url+(link.pdf?' · PDF':'');text.append(small);label.append(check,text);$('resources').append(label);});$('saved').value='';$('destination').value='';if(courses[data.course]){$('saved').value=data.course;$('destination').value=courses[data.course];}refresh();status((data.selected?'Collected selected text.':'Collected the visible pre-class work area.')+' Review the sources before continuing.'+(data.truncated?' Text exceeded 60,000 characters and was truncated. Select a smaller section.':''));}
async function collect(){if(!api){status('Preview mode. Load the extension in Chrome to collect a page, or try the sample.');return;}$('collect').disabled=true;try{const requested=Number(new URLSearchParams(location.search).get('tab'));const tab=requested?await chrome.tabs.get(requested):(await chrome.tabs.query({active:true,currentWindow:true}))[0];if(!tab?.id || !/^https?:/.test(tab.url || ''))throw Error('Open Forum pre-class work in a regular browser tab, then click the extension.');const [result]=await chrome.scripting.executeScript({target:{tabId:tab.id},func:collectPage});if(!result?.result?.text)throw Error('No visible pre-class work text found. Expand the pre-class work and try again.');render(result.result);}catch(e){status(e.message);}finally{$('collect').disabled=false;}}
$('collect').onclick=collect;
$('demo').onclick=()=>render({course:'CS142',title:'Session 4 · Languages & computation',url:'https://forum.minerva.edu/example',text:'CS142 · Session 4\nRead Chapter 3 before class. Focus on the distinction between syntax and meaning.\nStudy guide\nWhat makes a proof by induction valid?\nExplain the role of the inductive hypothesis.',questions:['What makes a proof by induction valid?','Explain the role of the inductive hypothesis.'],links:[{title:'Mathematics for Computer Science',url:'https://courses.csail.mit.edu/6.042/spring18/mcs.pdf',pdf:true,context:'Chapter 3'}]});
for(const id of ['course','title','source','questions','instructions','context','notes'])$(id).addEventListener('input',refresh);
function listCourses(){$('saved').replaceChildren(new Option('New destination',''),...Object.keys(courses).sort().map(c=>new Option(c,c)));}
$('saved').onchange=()=>{const c=$('saved').value;if(c){$('course').value=c;$('destination').value=courses[c];refresh();}};
$('save').onclick=async()=>{try{const course=$('course').value.trim();if(!course)throw Error('Enter a course name first.');const url=destination($('destination').value);if(!api)throw Error('Saving is available after loading the extension in Chrome.');courses[course]=url;await chrome.storage.local.set({courses});listCourses();$('saved').value=course;status('Course destination saved on this browser.');}catch(e){status(e.message);}};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('prompt').value);status('Copied. Paste into ChatGPT and click Send.');}catch{$('prompt').focus();$('prompt').select();status('Clipboard unavailable. The prompt is selected; press ⌘C or Ctrl+C.');}};
$('open').onclick=async()=>{try{const url=destination($('destination').value);if(!api)throw Error('Load the extension in Chrome to enable the ChatGPT handoff.');const result=await chrome.runtime.sendMessage({type:'handoff',url,prompt:$('prompt').value});if(result.error)throw Error(result.error);status('Opened ChatGPT. Your prompt will be inserted and sent automatically.');}catch(e){status(e.message);}};
if(api){({courses={}}=await chrome.storage.local.get('courses'));listCourses();if(new URLSearchParams(location.search).has('tab'))collect();}
