import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {collectPage} from '../extension/core.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const directory=await mkdtemp(join(tmpdir(),'preclass-test-'));
const extension=resolve('extension');
const context=await chromium.launchPersistentContext(directory,{channel:'chromium',headless:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});
try {
 const worker=context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
 const id=new URL(worker.url()).host;
 const page=await context.newPage();
 await page.route('https://forum.minerva.edu/**',route=>route.fulfill({contentType:'text/html',body:'<nav><a href="/home">Home</a></nav><main><h1>CS142 Session 4</h1><p>Read Chapter 3.</p><ul><li><a href="https://example.com/book.pdf">The textbook</a> — Chapter 3</li><li><a href="https://example.com/book.pdf">Duplicate</a></li><li hidden><a href="https://example.com/hidden">Hidden</a></li><li><a href="javascript:alert(1)">Unsafe</a></li></ul><p>Why does induction work?</p></main>'}));
 await page.goto('https://forum.minerva.edu/session');
 const data=await page.evaluate(collectPage);
 assert.equal(data.course,'CS142');assert.equal(data.links.length,1);assert.equal(data.links[0].pdf,true);assert.match(data.links[0].context,/Chapter 3/);assert.equal(data.questions.length,1);
 await page.evaluate(()=>{const r=document.createRange();r.selectNodeContents(document.querySelector('ul'));getSelection().removeAllRanges();getSelection().addRange(r);});
 const selected=await page.evaluate(collectPage);assert.equal(selected.selected,true);assert.ok(!selected.text.includes('Why does induction work?'));
 console.log('PASS collection: visible links, deduplication, context, selection');
 const popup=await context.newPage();const errors=[];popup.on('pageerror',e=>errors.push(e.message));
 await popup.goto(`chrome-extension://${id}/popup.html`);
 await popup.locator('#demo').click();
 assert.match(await popup.locator('#prompt').inputValue(),/Mathematics for Computer Science/);
 await popup.locator('#resource-0').uncheck();assert.match(await popup.locator('#prompt').inputValue(),/No reading links detected/);
 await popup.locator('#resource-0').check();
 await popup.locator('#destination').fill('https://chatgpt.com/c/test');await popup.locator('#save').click();
 await popup.waitForFunction(()=>document.querySelector('#status').textContent.includes('saved'));
 const stored=await worker.evaluate(()=>chrome.storage.local.get('courses'));assert.equal(stored.courses.CS142,'https://chatgpt.com/c/test');
 await popup.screenshot({path:resolve('preview.png'),fullPage:true});
 await context.route('https://chatgpt.com/**',route=>route.fulfill({contentType:'text/html',body:'<main><textarea id="prompt-textarea"></textarea><button id="send" onclick="window.sent=true">Send</button></main>'}));
 const opened=context.waitForEvent('page');await popup.locator('#open').click();const chat=await opened;
 await chat.waitForURL('https://chatgpt.com/c/test');
 await chat.waitForFunction(()=>document.querySelector('#prompt-textarea')?.value.includes('CS142'));
 assert.equal(await chat.evaluate(()=>window.sent),undefined);
 console.log('PASS extension UI, saved destination, service-worker handoff, insertion without sending');
 await context.unroute('https://chatgpt.com/**');
 await context.route('https://chatgpt.com/**',route=>route.fulfill({contentType:'text/html',body:'<textarea id="prompt-textarea">My existing draft</textarea>'}));
 const next=context.waitForEvent('page');await popup.locator('#open').click();const draft=await next;await draft.waitForURL('https://chatgpt.com/c/test');
 await draft.waitForFunction(()=>document.querySelector('div[style*="position: fixed"]'));
 assert.equal(await draft.locator('#prompt-textarea').inputValue(),'My existing draft');
 console.log('PASS existing draft preservation');
 await context.unroute('https://chatgpt.com/**');
 await context.route('https://chatgpt.com/**',route=>route.fulfill({contentType:'text/html',body:'<div id="prompt-textarea" contenteditable="true" style="min-height:50px"></div>'}));
 const richOpened=context.waitForEvent('page');await popup.locator('#open').click();const rich=await richOpened;
 await rich.waitForURL('https://chatgpt.com/c/test');
 await rich.waitForFunction(()=>document.querySelector('#prompt-textarea')?.innerText.includes('CS142'));
 assert.match(await rich.locator('#prompt-textarea').innerText(),/Mathematics for Computer Science/);
 console.log('PASS rich-text composer');
 const panelOpened=context.waitForEvent('page');await page.mouse.click(1180,675);const panel=await panelOpened;
 await panel.waitForURL(`chrome-extension://${id}/popup.html?tab=*`);
 await panel.waitForFunction(()=>document.querySelector('#review').hidden===false);
 assert.match(await panel.locator('#prompt').inputValue(),/The textbook/);
 console.log('PASS floating launcher to collection in extension review tab');
 assert.deepEqual(errors,[]);
} finally {await context.close();await rm(directory,{recursive:true,force:true});}
